[tasks.calibrate]
run = """
ros2 launch ur_robot_driver ur_control.launch.py \
  ur_type:=ur12e \
  use_mock_hardware:=true \
  headless_mode:=true \
  robot_ip:=192.168.56.101 \
  kinematics_params_file:="${PWD}/my_robot_calibration.yaml"
"""

[tasks.mock_control]
run = """
ros2 launch ur_robot_driver ur_control.launch.py \
  ur_type:=ur12e \
  use_mock_hardware:=true \
  headless_mode:=true \
  robot_ip:=192.168.56.101 \
  kinematics_params_file:="${PWD}/my_robot_calibration.yaml"
"""

[tasks.moveit]
run = """
ros2 launch ur_moveit_config ur_moveit.launch.py \
  ur_type:=ur12e \
  launch_rviz:=true
"""

[tasks.real_control]
run = """
ros2 launch ur_robot_driver ur_control.launch.py \
  ur_type:=ur12e \
  use_mock_hardware:=false \
  headless_mode:=true \
  robot_ip:=192.168.56.101 \
  kinematics_params_file:="${PWD}/my_robot_calibration.yaml"
"""

[tasks.simulated_robot]
run = {tasks = [ "mock_control", "moveit" ] }

[tasks.real_robot]
run = {tasks = [ "real_control", "moveit" ] }
